#!/bin/bash
# This script looks for recent disk access, and if nothing has changed, puts /dev/disk/by-id/${drive} into spindown mode.
# This script is copied from: https://forums.unraid.net/topic/92749-script-to-spindown-unassigned-usb-hdds/
# Set your drive identifiers (listed in /dev/disk/by-id/) ignoring characters after the last "-"
# e.g. listing: usb-WD_My_Passport_25E2_75831314363630505A37-0:0
#      becomes: usb-WD_My_Passport_25E2_75831314363630505A37
drives=(
  "<DRIVE_IDENTIFIER_1>"
  "<DRIVE_IDENTIFIER_2>"
)

# Set spindown delay based on time of day
current_time="$(date +'%k%M')"
lower_bound='0900'
upper_bound='2200'

if [ "${current_time}" -ge "${lower_bound}" -a "${current_time}" -lt "${upper_bound}" ]; then 
    SPINDOWN_DELAY=60
else
    SPINDOWN_DELAY=15
fi

# Uncomment to enable debug mode
# DEBUG=true

# Set directories for status and sensor files
STATUS_DIR="/dev/shm/hdd"
SENSORS_DIR="/dev/shm/ha-sensors"
mkdir -p "${STATUS_DIR}" "${SENSORS_DIR}"

current=`date`

do_device() {
    local device_id=$1
    device=`ls -l /dev/disk/by-id/ | grep ${device_id} | head -1 | tail -c4`
    filename="${STATUS_DIR}/diskaccess-${device_id}.status"
    sensor_file="${SENSORS_DIR}/${device_id}_status"

    # Check if the drive is awake or asleep
    is_awake=`smartctl --nocheck standby -i /dev/${device} | grep 'Power mode is' | egrep -c 'ACTIVE|IDLE'`

    if [ "${is_awake}" == "1" ]; then
        echo "on" > "${sensor_file}"
        if [ "$DEBUG" = true ]; then
            echo "${device} is awake"
        fi

        stat_new=$(grep "${device} " /proc/diskstats | tr -dc "[:digit:]")

        if [ ! -f "${filename}" ]; then
            echo ${current} "- ${filename} file does not exist; creating it now."
            echo ${stat_new} > ${filename}
        else
            stat_old=`cat ${filename} | tr -dc "[:digit:]"`

            # Calculate time since last use
            current_time=$(date +%s)
            last_mod=$(stat ${filename} -c %Y)
            seconds_ago=$(expr $current_time - $last_mod)
            minutes_ago=$(expr $seconds_ago / 60)

            if [ "$DEBUG" = true ]; then
                echo "${device} old stat: ${stat_old}"
                echo "${device} new stat: ${stat_new}"
                echo "${device} new stat modified ${minutes_ago} minutes ago"
            fi

            if [ "${stat_old}" == "${stat_new}" ]; then
                if [ $minutes_ago -ge $SPINDOWN_DELAY ]; then
                    echo ${current} "- Drive /dev/${device} is awake and hasn't been used in ${minutes_ago} minutes; spinning down"
                    hdparm -y /dev/${device} > /dev/null 2>&1
                else
                    echo ${current} "- Drive /dev/${device} was last used ${minutes_ago} minutes ago, less than spindown setting ($SPINDOWN_DELAY)"
                fi
            else
                echo ${current} "- Drive /dev/${device} has been used..."
                echo ${stat_new} > ${filename}
            fi
        fi
    else
        echo "off" > "${sensor_file}"
        if [ "$DEBUG" = true ]; then
            echo "${device} is asleep"
        fi
    fi
}

# Process each drive
for device_id in "${drives[@]}"
do
    do_device ${device_id}
done
