#######################################################################################
# Authelia configuration
# 
# For this config to work you need to add the filter template variable:
# 'X_AUTHELIA_CONFIG_FILTERS'='template'
#  
# Command for generating secrets
# openssl rand -base64 32
#
# Command for generating oidc key
# openssl genrsa -out rsa.2048.key 2048
#
# Command for hashing immich_client_secret
# docker exec Authelia authelia crypto hash generate pbkdf2 --password 'your-secret'
#
#######################################################################################

access_control:
  default_policy: deny
  rules:
    # authelia
    - domain: 
        - 'auth.{{ secret "/config/secrets/domain" | trim }}'
      policy: bypass

    # Services with app
    - domain:
        - 'vuetorrent.{{ secret "/config/secrets/domain" | trim }}'
        - 'qbittorrent.{{ secret "/config/secrets/domain" | trim }}'
        - 'torrent.{{ secret "/config/secrets/domain" | trim }}'
        - 'paperless.{{ secret "/config/secrets/domain" | trim }}'
      resources:
        - "^/api([/?].*)?$"
      policy: bypass

    # Filbrowser share bypass
    - domain:
        - 'files.{{ secret "/config/secrets/domain" | trim }}'
        - 'filebrowser.{{ secret "/config/secrets/domain" | trim }}'
      resources:
        - "^/api/public/dl/.*"
        - "^/share/.*"
        - "^/static/js/.*"
        - "^/static/css/.*"
        - "^/static/img/.*"
        - "^/static/themes/.*"
        - "^/static/fonts/.*"
        - "^/static/assets/.*"
      policy: bypass

    # VaultWarden
    - domain: 
        - 'vaultwarden.{{ secret "/config/secrets/domain" | trim }}'
        - 'bitwarden.{{ secret "/config/secrets/domain" | trim }}'
      policy: deny
      resources:
        - "^/admin.*$"
    - domain:
        - 'vaultwarden.{{ secret "/config/secrets/domain" | trim }}'
        - 'bitwarden.{{ secret "/config/secrets/domain" | trim }}'
      policy: bypass

    # catch-all
    - domain:
        - '*.{{ secret "/config/secrets/domain" | trim }}'
      policy: two_factor


theme: dark
identity_validation:
  reset_password:
    jwt_secret: '{{ secret "/config/secrets/jwt_secret" | trim }}'

server:
  address: '{{ secret "/config/secrets/server_adress" | trim }}'
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false

log:
  level: info

totp:
  issuer: '{{ secret "/config/secrets/domain" | trim }}'
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 8
        salt_length: 16

webauthn:
  disable: false
  display_name: 'My Security Keys'
  attestation_conveyance_preference: 'none'
  timeout: 60s
  selection_criteria:
    user_verification: 'preferred'

session:
  name: authelia_session
  same_site: lax
  secret: '{{ secret "/config/secrets/session_secret" | trim }}'
  expiration: 1h
  inactivity: 5m
  remember_me: 1w
  cookies:
    - domain: '{{ secret "/config/secrets/domain" | trim }}'
      authelia_url: 'https://auth.{{ secret "/config/secrets/domain" | trim }}'
      default_redirection_url: 'https://{{ secret "/config/secrets/domain" | trim }}'
  redis:
    host: redis
    port: 6379
    password: '{{ secret "/config/secrets/redis_password" | trim }}'
    timeout: '30s'
    max_retries: 10
    database_index: 2
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: '{{ secret "/config/secrets/storage_encryption_key" | trim }}'
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: '{{ secret "/config/secrets/oidc_hmac_secret" | trim }}'
    jwks:
      - key_id: 'authelia'
        algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/config/secrets/rsa.2048.key" | mindent 10 "|" | msquote }}
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'RS256'
    discovery_signed_response_key_id: 'authelia'
    require_pushed_authorization_requests: false
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://immich.{{ secret "/config/secrets/domain" | trim }}'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'immich'
        client_name: 'Immich'
        client_secret: '{{ secret "/config/secrets/immich_client_secret" | trim }}'
        public: false
        authorization_policy: 'two_factor'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - 'app.immich:///oauth-callback'
          - 'https://immich.{{ secret "/config/secrets/domain" | trim }}/auth/login'
          - 'https://immich.{{ secret "/config/secrets/domain" | trim }}/user-settings'
          - 'https://immich.{{ secret "/config/secrets/domain" | trim }}/api/oauth/mobile-redirect'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_post'
